Leanplum/Leanplum-Unity-SDK

- LeanplumSample/Assets/WebPlayerTemplates/DoNotCompile/Leanplum/LeanplumUnityHelper.cs
Fixes https://github.com/Leanplum/Leanplum-Unity-SDK/issues/9
> Fixed asset bundle related errors with Unity 2017

- LeanplumSample/Assets/Plugins/Android/.gitignore
- LeanplumSample/Assets/Plugins/iOS/Leanplum.framework/Headers/Leanplum.h
- Makefile
- build.sh
`make unitypackage` now creates a unitypackage.
> Release Unity with newest SDK versions

- Android/src/main/java/com/leanplum/UnityBridge.java
- LeanplumSample/Assets/LeanplumSDK/Leanplum.cs
- LeanplumSample/Assets/LeanplumSDK/LeanplumAndroid/LeanplumAndroid.cs
- LeanplumSample/Assets/LeanplumSDK/LeanplumIOS/LeanplumIOS.cs
- LeanplumSample/Assets/LeanplumSDK/LeanplumNative/LeanplumNative.cs
- LeanplumSample/Assets/LeanplumSDK/LeanplumSDKObject.cs
> E2-1079 Adding support for additional setDeviceLocationWithLatitude

- Makefile
> Preparing for Unity 1.6.3 release

- LeanplumSample/Assets/LeanplumSDK/SharedConstants.cs
Fixes #41 
updated SDK version to be 1.6.5 (latest release version)
> updated version to be latest release version

- LeanplumSample/Assets/Plugins/iOS/Leanplum.framework.meta
Fixes #40 
enabled embedded binaries option for framework
> updated framework inclusion settings to automatically add to embedded binaries

- LeanplumSample/Assets/LeanplumSDK/LeanplumNative/Constants.cs
- LeanplumSample/Assets/LeanplumSDK/LeanplumNative/LeanplumSocket.cs
When connecting to dev sockets, use https and port 443
> Secure connection in dev mode

- LeanplumSample/Assets/LeanplumSDK/LeanplumAndroid/LeanplumAndroid.cs
JIRA Issue        | [E2-2023](https://leanplum.atlassian.net/browse/E2-2023)
People Involved   | @milos1290
> E2-2023: Fixing an issue with initialization

- LeanplumSample/Assets/LeanplumSDK/LeanplumNative/Constants.cs
- LeanplumSample/Assets/LeanplumSDK/LeanplumNative/LeanplumRequest.cs
- LeanplumSample/Assets/LeanplumSDK/LeanplumNative/UnityWebResponse.cs
- LeanplumSample/Assets/LeanplumSDK/LeanplumNative/Util.cs
- LeanplumSample/Assets/LeanplumSDK/LeanplumNative/WebResponse.cs
- LeanplumSample/Assets/LeanplumSDK/LeanplumUnityHelper.cs
JIRA Issue        | [LP-11139](https://leanplum.atlassian.net/browse/LP-11139)
People Involved   | @milos1290
> [LP-11139] Fixing an issue with status codes

- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumActionManager.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumNative.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/NativeActionContext.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/Networking/LeanplumSocket.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/VarCache.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Utilities/Constants.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Utilities/SocketWrapper.cs
JIRA Issue        | [SDK-225](https://leanplum.atlassian.net/browse/SDK-225)
Trigger In-app message when Preview is sent from the Dashboard through the Web Socket.
> [SDK-225] IAM Preview

- Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/LeanplumAndroid.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumApple.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Leanplum.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/LeanplumSDKObject.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumNative.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/VarCache.cs
JIRA Issue        | [SDK-250](https://leanplum.atlassian.net/browse/SDK-250)
> [SDK-250] Add Manual Sync Variables method

- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumActionManager.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/MessageTemplates/EditorMessageTemplates.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/NativeActionContext.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Utilities/Constants.cs
Fix View event and Action events tracking.
Refactor access modifiers, comments, arguments.
> Fix and Refactor Actions

- Leanplum-Android-SDK-Unity/android-unity-wrapper/src/main/java/com/leanplum/UnityActionContextBridge.java
- Leanplum-Android-SDK-Unity/android-unity-wrapper/src/main/java/com/leanplum/UnityBridge.java
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/ActionContextAndroid.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/LeanplumAndroid.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/ActionContextApple.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumApple.cs
- Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumActionContextBridge.h
- Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumActionContextBridge.mm
- Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumIOSBridge.mm
JIRA Issue        | [SDK-281](https://leanplum.atlassian.net/browse/SDK-281)
Add messageId to ActionContext
Fix getBooleanNamed
> Add messageId to ActionContext

- Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/ActionContextAndroid.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/ActionContextApple.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/NativeActionContext.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/Utilities/Util.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/VarCache.cs
JIRA Issue | [SDK-284](https://leanplum.atlassian.net/browse/SDK-284)
Handle List values in Action Context arguments 
* Fix merging of list values from the server into the action definition arguments. 
* Cast the collections to the correct collection and elements types.
* Convert to correct type from mobile to Native
> Handle ActionContext Arg collections

- Leanplum-Unity-SDK/Assets/LeanplumSDK/LeanplumUnityHelper.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumNative.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/VarCache.cs
JIRA Issue        | [SDK-341](https://leanplum.atlassian.net/browse/SDK-341)
Sync Inbox messages on ForceContentUpdate
Move FCU in LeanplumNative to access the Inbox instance.
> Fix FCU Inbox

- Leanplum-Android-SDK-Unity/android-unity-wrapper/src/main/java/com/leanplum/UnityBridge.java
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/LeanplumAndroid.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumApple.cs
- Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumIOSBridge.mm
Cherry-pick OnAction and Vars Diffs from Master into LTS branch.
> [CP] OnAction and Vars Diffs

- Leanplum-Android-SDK-Unity/android-unity-wrapper/src/main/java/com/leanplum/UnityBridge.java
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/LeanplumAndroid.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumApple.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Leanplum.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/LeanplumSDKObject.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumNative.cs
- Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumIOSBridge.mm
JIRA Issue        | [SDK-420](https://leanplum.atlassian.net/browse/SDK-420)
JIRA Issue        | [SDK-321](https://leanplum.atlassian.net/browse/SDK-321)
Enable ActionContext creation based on action Id. Trigger action.
Example code:
```
string id = "6458165843066880";
ActionContext context = Leanplum.CreateActionContextForId(id);
if (context != null)
{
string title = context.GetStringNamed("Title");
string message = context.GetStringNamed("Message");
}
...
Leanplum.TriggerActionForId("6458165843066880");
```
Manual
Yes
> [SDK-420] Create action context and trigger

- Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/LeanplumAndroid.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumApple.cs
JIRA Issue        | [SDK-638](https://leanplum.atlassian.net/browse/SDK-638)
Leanplum.Started event is not executed in some cases. Implementation differs from `LeanplumNative` one which deceives users when testing in Editor and on a device.
Reproduces if the start event is attached later on. Example:
```
void Start()
{
Leanplum.Started += Leanplum_Started;
Leanplum.Start();
StartCoroutine(ExampleCoroutine());
Leanplum.Started += Leanplum_Started_2;
}
IEnumerator ExampleCoroutine()
{
yield return new WaitForSeconds(15);
Leanplum.Started += Leanplum_Started_3;
}
private void Leanplum_Started(bool success)
{
}
private void Leanplum_Started_2(bool success)
{
}
private …
```
> Fix Started event

- Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/AppleVar.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumApple.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumInboxApple.cs
- Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumIOSBridge.mm
JIRA Issue        | [SDK-644](https://leanplum.atlassian.net/browse/SDK-644)
People Involved   | @nzagorchev
> Prefix iOS functions

- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumNative.cs
I noticed this issue while writing some tests that set Leanplum's test mode to true.
> Fixed ForceContentUpdate not calling its callback in test mode

- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/NativeActionContext.cs
JIRA Issue        | [SDK-2360](https://wizrocket.atlassian.net/browse/SDK-2360)
Use parent id for embedded chained messages' id.
Set the id for in-app chained using "Chain to new message" in Messaging.
> Use parent id for chained messages

- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/Utilities/Util.cs
JIRA Issue        | [SDK-2367](https://wizrocket.atlassian.net/browse/SDK-2367)
Fix Variables group/dictionary values when the variable contains nested groups as well as different level single values.
Reproducible with the following variable:
_test_group_ (group):
- 0: (group)
- a
- 1: (group)
- a
- b
Variable in code:
```csharp
var defaultValue = new Dictionary<string, object>();
Var<Dictionary<string, object>> variable = Var.Define("test_group", defaultValue);
```
Actual: the 0 group is missing from the variable value
Do not clear the destination dictionary.
Refactoring.
Manual
Tested using the following variable setup:
_test_group_ (group):
- 0: (group)
- a
- b
- …
> Fix group values

- Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/ActionContextAndroid.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/ActionContextApple.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/LeanplumInbox.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/NativeActionContext.cs
- Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumActionContextBridge.mm
JIRA Issue        | [SDK-2503](https://wizrocket.atlassian.net/browse/SDK-2503)
Fixes for Parsing and Converting
> Fixes for Parsing and Converting

- Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/VarCache.cs
JIRA Issue        | [SDK-2978](https://wizrocket.atlassian.net/browse/SDK-2978)
Improve `VarCache.DeserializeEncryptedData`
> Improve VarCache DeserializeEncryptedData

- Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/LeanplumAndroid.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumApple.cs
- Leanplum-Unity-SDK/Assets/LeanplumSDK/Leanplum.cs
JIRA Issue        | [SDK-3330](https://wizrocket.atlassian.net/browse/SDK-3330)
Add additional checks when parsing NativeCallback messages.
Yes
> Prevent errors when parsing NativeCallback messages

- Leanplum-Unity-SDK/Assets/CleverTap/Editor/AndroidProjectPostProcessor.cs
- Leanplum-Unity-SDK/Assets/CleverTap/Editor/AndroidProjectPostProcessor.cs.meta
- Leanplum-Unity-SDK/Assets/CleverTap/Editor/EditorUtils.cs
- Leanplum-Unity-SDK/Assets/CleverTap/Editor/IOSPostBuildProcessor.cs
- Leanplum-Unity-SDK/Assets/CleverTap/Plugins/Android/clevertap-android-wrapper.androidlib/src/main/java/com/clevertap/unity/CleverTapLifecycleCallbacks.java
- Leanplum-Unity-SDK/Assets/CleverTap/Plugins/Android/clevertap-android-wrapper.androidlib/src/main/java/com/clevertap/unity/CleverTapLifecycleCallbacks.java.meta
- Leanplum-Unity-SDK/Assets/CleverTap/Plugins/Android/clevertap-android-wrapper.androidlib/src/main/java/com/clevertap/unity/CleverTapUnityAPI.java
- Leanplum-Unity-SDK/Assets/CleverTap/Runtime/Constants/CleverTapVersion.cs
- Leanplum-Unity-SDK/Assets/Editor/PackageImporter.cs
- Leanplum-Unity-SDK/Assets/ExternalDependencyManager/Editor/1.2.185/Google.IOSResolver.dll.meta
- Leanplum-Unity-SDK/Assets/ExternalDependencyManager/Editor/1.2.185/Google.JarResolver.dll.meta
- Leanplum-Unity-SDK/Assets/ExternalDependencyManager/Editor/1.2.185/Google.PackageManagerResolver.dll.meta
- Leanplum-Unity-SDK/Assets/ExternalDependencyManager/Editor/LICENSE.meta
Update CleverTap package to 5.0.1
> Update CleverTap to 5.0.1
