Android/src/main/java/com/leanplum/UnityBridge.java
LeanplumSample/Assets/LeanplumSDK/Leanplum.cs
LeanplumSample/Assets/LeanplumSDK/LeanplumAndroid/LeanplumAndroid.cs
LeanplumSample/Assets/LeanplumSDK/LeanplumIOS/LeanplumIOS.cs
LeanplumSample/Assets/LeanplumSDK/LeanplumNative/LeanplumNative.cs
LeanplumSample/Assets/LeanplumSDK/LeanplumSDKObject.cs
LeanplumSample/Assets/Plugins/iOS/LeanplumIOSBridge.mm

exposed track purchase api for Unity implementations that cannot use the generic track all purchases setup

exposed track purchase api

---

LeanplumSample/Assets/Plugins/iOS/LeanplumIOSBridge.mm

The documented and android behaviour of the SDK is to set the deviceId as the userId when no userId is provided. However the iOS bridge file is setting an empty string in these instances. This PR fixes that inconsistency.

fixed issue with iOS behaviour when no userId

---

LeanplumSample/Assets/LeanplumSDK/LeanplumNative/LeanplumNative.cs

Without this, performing some actions like `SetUserAttributes` throws an error in test mode.

Set calledStart in Test Mode

---

LeanplumSample/Assets/LeanplumSDK/Leanplum.cs
LeanplumSample/Assets/LeanplumSDK/LeanplumAndroid/LeanplumAndroid.cs
LeanplumSample/Assets/LeanplumSDK/LeanplumIOS/LeanplumIOS.cs
LeanplumSample/Assets/LeanplumSDK/LeanplumNative/LeanplumNative.cs
LeanplumSample/Assets/LeanplumSDK/LeanplumNative/UnityCompatibilityLayer.cs
LeanplumSample/Assets/LeanplumSDK/LeanplumSDKObject.cs
LeanplumSample/Assets/LeanplumSDK/LeanplumUnityHelper.cs

We had several warnings in the SDK. Some were caused by the old track purchase methods being marked as obsolete, but those obsolete methods still being called and overridden. Adding the obsolete attribute to these overrides fixed those warnings.
We also had warnings due to old Unity and C# methods being called:
- ~~UnityWebRequest.SendWebRequest instead of UnityWebRequest.Send. The new method is supported by Unity 2017.2 and later, so all the currently publicly supported Unity versions.~~ Just got fixed on master.
- TimeZoneInfo.Local instead of TimeZone.CurrentTimeZone. I couldn't track down when Unity started supporting it, but it's been supported by .NET for the past 10 years.
- Uri.EscapeUriString instead of WWW.EscapeURL. Supported by .NET for the past 18 years.

Fixed warnings in the SDK

---

Leanplum-Android-SDK-Unity/android-unity-wrapper/src/main/java/com/leanplum/UnityBridge.java
Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/LeanplumAndroid.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumApple.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/EventsUploadInterval.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/EventsUploadInterval.cs.meta
Leanplum-Unity-SDK/Assets/LeanplumSDK/Leanplum.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/LeanplumSDKObject.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumNative.cs

JIRA Issue        | [SDK-202](https://leanplum.atlassian.net/browse/SDK-202)
Adds the option to set the upload interval from Unity. Supported on iOS and Android only.
[Android PR](https://github.com/Leanplum/Leanplum-Android-SDK/pull/428/files)

[SDK-202] Add set upload interval for Android

---

Leanplum-Unity-SDK/Assets/LeanplumSDK/Utilities/MiniJSON.cs

JIRA Issue        | [SDK-226](https://leanplum.atlassian.net/browse/SDK-226)
Double and long serialization/deserialization does not work correctly.
Tested using the following values:
```csharp   
ulong n = 12156480978394720353;
double d = 0.000000001;
decimal dc = 5.6789012345678901234567890123456789012345M;
var currentCul = CultureInfo.CurrentCulture;
CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo("DE");
var dict = new Dictionary<string, object> { { "d", d }, { "l", n }, { "ll",  0}, { "dd", 0.12 }, { "dc", dc } };
var test = Json.Serialize(dict);
dict = Json.Deserialize(test) as Dictionary<string, object>;
```

[SDK-226] Fix double and long deserialization

---

Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumApple.cs
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumIOSBridge.mm

JIRA Issue        | [SDK-224](https://leanplum.atlassian.net/browse/SDK-224)
Adds the option to set the upload interval from Unity on iOS.
[iOS PR](https://github.com/Leanplum/Leanplum-iOS-SDK/pull/413)

[SDK-224] Add iOS setEventsUploadInterval

---

Leanplum-Android-SDK-Unity/android-unity-wrapper/build.gradle
Leanplum-Android-SDK-Unity/android-unity-wrapper/src/main/java/com/leanplum/UnityBridge.java
Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/LeanplumInboxAndroid.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumInboxApple.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/LeanplumInbox.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumInboxNative.cs
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumIOSBridge.mm

JIRA Issue        | [SDK-266](https://leanplum.atlassian.net/browse/SDK-266)
Implement the Inbox DownloadMessage methods available in the native iOS and Android SDKs (3.1.1 and 5.5.0).
Implement the method in the Leanplum Native Inbox, iOS and Android.
Use the native callbacks to communicate.

[SDK-266] Add Inbox DownloadMessages

---

Leanplum-Android-SDK-Unity/android-unity-wrapper/src/main/java/com/leanplum/UnityActionContextBridge.java
Leanplum-Android-SDK-Unity/android-unity-wrapper/src/main/java/com/leanplum/UnityBridge.java
Leanplum-Unity-SDK/Assets/LeanplumSDK/ActionContext.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/ActionContextAndroid.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/ActionContextApple.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/ActionArgs.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/NativeActionContext.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/Utilities/Util.cs
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumActionContextBridge.mm
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumIOSBridge.mm
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumUnityHelper.h
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumUnityHelper.mm

JIRA Issue        | [SDK-287](https://leanplum.atlassian.net/browse/SDK-287)
Fix definition of Actions - allow null as defaultValue. This will provide parity between Unity and iOS/Android.
Enable defining Colors. Use int as the color type (Android Color) and convert to the correct types on each platform.
Enable defining Files. Return the file path or URL.
Add support for Color and Files.
Use integer/long to pass the Color values between Unity and iOS/Android.
Implement registering Files and getting the file from the Action Context.
Returns asset URL (download URL from LP) on Unity Native/Editor.
Returns file path (file://) on Android and iOS.

Action context fixes

---

Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumInboxNative.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/NativeActionContext.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/VarCache.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Utilities/Constants.cs

JIRA Issue        | [SDK-293](https://leanplum.atlassian.net/browse/SDK-293)
Implement Inbox Open Action handling in Unity Native.
Build ActionContext for the Open Action of the Inbox Message. Run the Open Action as tracked action to execute the Open Action and track an Open event.
Manual testing with Open Actions:
- Open URL with default URL and set URL
- Chain to a new message
- Chain to a new message with Open Action itself
- Campaign Composer chained Open Action
Yes

[SDK-293] Implement Native Inbox Open Action

---

Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumNative.cs

JIRA Issue        | [SDK-351](https://leanplum.atlassian.net/browse/SDK-351)
The `onVariablesChangedAndNoDownloadsPending` callback is executed twice on Start. The callback is executed from `VarCache.Update` and immediately from `LeanplumRequest.NoPendingDownloads` if there are no pending downloads.
The latter is executed on iOS and Android only if a `downloadFile` request is started. This differs from Unity Native where the handler is executed immediately when added to the `LeanplumRequest` if there are no Pending Downloads.
Move the `LeanplumRequest.NoPendingDownloads` so it is executed only when there are pending downloads. Otherwise, the callback is executed from `VarCache.Update`, resulting in …

Move Request NoPendingDownloads

---

Leanplum-Unity-SDK/Assets/LeanplumSDK/ActionContext.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/ActionContextAndroid.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/LeanplumAndroid.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/ActionContextApple.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumApple.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/NativeActionContext.cs

JIRA Issue        | [SDK-350](https://leanplum.atlassian.net/browse/SDK-350)
Expose action/messageId in Action Context.

[SDK-350] Add message Id to Action Context

---

Leanplum-Android-SDK-Unity/android-unity-wrapper/src/main/java/com/leanplum/UnityBridge.java
Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/LeanplumInboxAndroid.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumInboxApple.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/LeanplumInbox.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumInboxNative.cs
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumIOSBridge.mm

JIRA Issue        | [SDK-353](https://leanplum.atlassian.net/browse/SDK-353)
Expose MarkAsRead method
Make the MarkAsReads public and call the corresponding method on iOS and Android.

[SDK-353] Expose Inbox MarkAsRead

---

Leanplum-Android-SDK-Unity/android-unity-wrapper/src/main/java/com/leanplum/UnityBridge.java
Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/LeanplumAndroid.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumApple.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Leanplum.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/LeanplumSDKObject.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumNative.cs
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumIOSBridge.mm

JIRA Issue        | [SDK-395](https://leanplum.atlassian.net/browse/SDK-395)
Expose the Variables Diffs
Example Usage:
```
Debug.Log($"Leanplum Vars: {Leanplum.Vars()}");
Debug.Log($"Leanplum Vars Count: {Leanplum.Vars().Count}");
var vals = Leanplum.Vars().Values.Select(c => c.ToString()).ToList();
Debug.Log($"Leanplum Vars Values: {string.Join(",", vals)}");
```
Manual
Yes

Expose Vars Diffs

---

Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/MessageTemplates/EditorMessageTemplates.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Utilities/MiniJSON.cs

JIRA Issue        | [SDK-396](https://leanplum.atlassian.net/browse/SDK-396)
If Decryption fails, `String.Empty` is returned. This cannot be parsed by MiniJSON and throws an exception.
Such exception can be thrown in `VarCache.LoadDiffs` when calling `ApplyVariableDiffs`.
Return null for `String.Empty` when parsing JSON.
```
var test = LeanplumSDK.MiniJSON.Json.Deserialize("");
```
The above line was previously throwing an exception:
```
OverflowException: Value was either too large or too small for a character.
at System.Convert.ToChar (System.Int32 value)
```
It now returns null.
Other cases remain unchanged:
```
var test = LeanplumSDK.MiniJSON.Json.Deserialize(" "); // returns null
var test = …
```

[SDK-396] Parse correctly empty string

---

Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/LeanplumAndroid.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumApple.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Leanplum.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/LeanplumSDKObject.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/LeanplumSecuredVars.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumNative.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/VarCache.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Utilities/Constants.cs

JIRA Issue        | [SDK-408](https://leanplum.atlassian.net/browse/SDK-408)
Unity Native Secured Vars.
`LeanplumSecuredVars` will contain the JSON and signature of the variables.
Accessed via `Leanplum.SecuredVars()`.

[SDK-408] Unity Secured vars

---

Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/MessageTemplates/EditorMessageTemplates.cs

The GenericActionDefinition logs cast error when Rich Interstitial is shown in Unity Editor due to the Fonts field which is not a primitive object.
Error logged (exception is caught):
`Error casting value for name: messageConfig.vars. Exception: Object must implement IConvertible.`
Fallback to object and do not convert and cast explicitly.
Yes

Prevent cast error

---

Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumNative.cs

JIRA Issue        | [SDK-432](https://leanplum.atlassian.net/browse/SDK-432)
If the Leanplum Start fails, load the variables from the cache using `VarCache.LoadDiffs`. Currently, the code calls `ApplyVariableDiffs`, which results in the same behavior.
To align the Unity SDK with the iOS and Android ones, call `VarCache.LoadDiffs` to load the content from the cache. It internally calls `ApplyVariableDiffs` with the cached values.
No behavior changes based on testing.
Use `VarCache.LoadDiffs`.
Manual testing. Tested the main callbacks and monitoring VarCache values.
```
hello = Var<string>.Define("hello", "test");
Leanplum.Started += Leanplum_Started;
Leanplum.VariablesChanged += …
```

[SDK-432] Load diffs on start error

---

Leanplum-Android-SDK-Unity/android-unity-wrapper/src/main/java/com/leanplum/UnityActionContextBridge.java
Leanplum-Android-SDK-Unity/android-unity-wrapper/src/main/java/com/leanplum/UnityBridge.java
Leanplum-Unity-SDK/Assets/LeanplumSDK/ActionContext.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/ActionContextAndroid.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/LeanplumAndroid.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/ActionContextApple.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumApple.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumActionManager.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumNative.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/MessageTemplates/EditorMessageTemplates.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/NativeActionContext.cs
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumActionContextBridge.h
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumActionContextBridge.mm
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumIOSBridge.h
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumIOSBridge.mm

JIRA Issue        | [SDK-448](https://leanplum.atlassian.net/browse/SDK-448)
Enables setting an `ActionContext.ActionResponder` responder to be invoked when an action is run - for example, a button click or message dismiss click (by a dismiss button click or outside tap). The responder is set to an ActionContext instance. This needs to be implemented inside an `OnAction` responder. It works for custom message templates as well.
Example code:
```csharp
ActionContext.ActionResponder runActionResponder = new ActionContext.ActionResponder((context) =>
{
Debug.Log($"ActionResponder: runActionResponder name: {context.Name}"); // Example: Accept action, Dismiss action, Select button 1 action …
```

[SDK-448] Action named responder

---

Leanplum-Android-SDK-Unity/android-unity-wrapper/src/main/java/com/leanplum/UnityBridge.java
Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/LeanplumAndroid.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumApple.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/LeanplumSecuredVars.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Utilities/Constants.cs
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumIOSBridge.mm

JIRA Issue        | [SDK-435](https://leanplum.atlassian.net/browse/SDK-435)
_Requires SecuredVars implementation in iOS and Android SDKs._
Get the SecuredVars from mobile SDK, serialize and send to Unity. Deserialize into `LeanplumSecuredVars` object in Unity.

[SDK-435] SecuredVars iOS and Android

---

build.sh

JIRA Issue        | [SDK-481](https://leanplum.atlassian.net/browse/SDK-481)
The build script replaces the SDK_VERSION string to the version specified in it. This also replaced the SDK_VERSION string under Constants -> Params.
Replace the 1st occurrence of the string using awk.
Manual

[SDK-481] Change 1st occurrence of version only

---

Leanplum-Android-SDK-Unity/android-unity-wrapper/src/main/java/com/leanplum/UnityBridge.java
Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/LeanplumAndroid.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumApple.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Leanplum.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/LeanplumSDKObject.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Utilities/Constants.cs
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumIOSBridge.mm

JIRA Issue        | [SDK-484](https://leanplum.atlassian.net/browse/SDK-484)
JIRA Issue        | [SDK-483](https://leanplum.atlassian.net/browse/SDK-483)
Enables setting Log level on iOS and Android.
Enables MiPush setting of key and id.
The Android implementation is a cherry-pick from the MiPush support package (code changes + unity package).
Adds LogLevel enum to bridge iOS and Android log levels.
Yes

[SDK-484] Enable setting Log level. Enable MiPush.

---

Leanplum-Android-SDK-Unity/android-unity-wrapper/src/main/java/com/leanplum/UnityBridge.java
Leanplum-Unity-SDK/Assets/LeanplumSDK/LeanplumInbox.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumInboxNative.cs
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumIOSBridge.mm

Access the app inbox message data from Advanced data in Unity, iOS, and Android.
Get the data from the message vars field on Unity Native. Load from Preferences since it is already saved as part of the ActionContext (messageData).
Include the data field in the serialized JSON from Android and iOS.
Yes

Expose App inbox message data

---

Leanplum-Android-SDK-Unity/android-unity-wrapper/src/main/java/com/leanplum/UnityBridge.java

JIRA Issue        | [SDK-704](https://leanplum.atlassian.net/browse/SDK-704)
Execute `UnitySendMessage` in parallel in the background using `OperationQueue`.

Send message in parallel using OperationQueue

---

Leanplum-Android-SDK-Unity/android-unity-wrapper/build.gradle
Leanplum-Android-SDK-Unity/android-unity-wrapper/src/main/java/com/leanplum/UnityBridge.java
Leanplum-Android-SDK-Unity/build.gradle
Leanplum-Unity-SDK/Assets/LeanplumSDK/Android/LeanplumAndroid.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumApple.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Leanplum.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/LeanplumSDKObject.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumNative.cs
Leanplum-Unity-SDK/Assets/Plugins/Android/mainTemplate.gradle
Leanplum-Unity-SDK/Assets/Plugins/Android/settingsTemplate.gradle
Leanplum-Unity-SDK/Assets/Plugins/Android/settingsTemplate.gradle.meta

… source.
JIRA Issue        | [SDK-2377](https://wizrocket.atlassian.net/browse/SDK-2377)
People Involved   | @hborisoff 
1. Expose `Leanplum.addOnceVariablesChangedAndNoDownloadsPendingHandler` from Android and Native. There is an empty method for iOS.
2. Enable `android-unity-wrapper` module to be accessible by source code when compiling the exported Android project from Unity. To enable it follow the steps from `settings.gradle` file. The exported Android project must be in the root directory of the repository.

Expose 'addOnceVariablesChangedAndNoDownloadsPendingHandler' for Android and Native

---

Leanplum-Unity-SDK/Assets/LeanplumSDK/Prefab/LeanplumWrapper.cs

JIRA Issue        | [SDK-2476](https://wizrocket.atlassian.net/browse/SDK-2476)
`Application.isEditor` check incorrectly returns false, resulting in the LeanplumApple or LeanplumAndroid SDK being used.
This reproduces when using the simulator on LTS 2020 (2020.3.30f1) with the [Device Simulator package](https://docs.unity3d.com/Packages/com.unity.device-simulator@3.0/manual/index.html).
The check correctly returns true if using LTS 2021 (2021.3.15f1) since the package is built in.
For more context check the JIRA and [this unity forum thread](https://forum.unity.com/threads/how-to-know-if-a-script-is-running-inside-unity-editor-when-using-device-simulator.921827/#post-6 …

Fix isEditor when using simulator

---

Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumNative.cs

JIRA Issue        | [SDK-2359](https://wizrocket.atlassian.net/browse/SDK-2359)
Leanplum Socket is not supported in WebGL.
Issue: #124

Fix WebGL build

---

Leanplum-Unity-SDK/Assets/Editor/LeanplumApplePostProcessor.cs
Makefile
build.sh

JIRA Issue        | [SDK-2632](https://wizrocket.atlassian.net/browse/SDK-2632)
Leanplum iOS SDK Frameworks are now zipped in `Leanplum.zip` file. All dependencies need to be added to the iOS Plugin.
- Use `Leanplum.zip` file. Add Leanplum, CleverTapSDK and SDWebImage xcframeworks. This zip also contains Leanplum Location xcframeworks which are not included by default and should not be added to Unity.
- Update `LeanplumApplePostProcessor`:
- Set the correct slice based on `BuildTarget` for all frameworks
- Disable bitcode for all Unity targets since it is now deprecated
- Remove build script for signing - no longer needed with the new setup
- Delete remove-simulator …

iOS dynamic framework updates

---

Leanplum-Unity-SDK/Assets/LeanplumSDK/Native/LeanplumNative.cs

JIRA Issue        | [SDK-2979](https://wizrocket.atlassian.net/browse/SDK-2979)
JIRA Issue        | [SDK-767](https://leanplum.atlassian.net/browse/SDK-767)
Unity Native - Fix the `userId` argument in `SetUserId` and `Start` when setting a new user id.
[SDK-767]: https://leanplum.atlassian.net/browse/SDK-767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix userId and newUserId args

---

Leanplum-Unity-SDK/Assets/Editor/LeanplumApplePostProcessor.cs
Leanplum-Unity-SDK/Assets/LeanplumSDK/Apple/LeanplumApple.cs
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumIOSBridge.mm
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumUnityAppController.h
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumUnityAppController.h.meta
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumUnityAppController.m
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumUnityAppController.m.meta
Leanplum-Unity-SDK/Assets/Plugins/iOS/LeanplumUnityConstants.h

Update iOS CleverTap initialization.
Uses changes in https://github.com/CleverTap/clevertap-unity-sdk/pull/151

Update iOS CleverTap initialization
